# Generated by Django 5.2.6 on 2025-09-28 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Действие')),
                ('sign_pleasant', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('period', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Периодичность', null=True)),
                ('award', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вознаграждение')),
                ('lead_time', models.PositiveSmallIntegerField(blank=True, default=60, help_text='Время выполнения в секундах', null=True)),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак публичности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_habit', models.ForeignKey(blank=True, limit_choices_to={'sign_pleasant': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_habit', to='tracker.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': ('Привычки',),
                'ordering': ['created_at'],
            },
        ),
    ]
